using System.Net.Http.Headers;
using System.Text;

namespace BotAPI.Utility;

public static class SvcConnector
{
    private static readonly HttpClient Client;

    static SvcConnector()
    {
        Client = new HttpClient();
        Client.DefaultRequestHeaders.Accept.Clear();
        Client.DefaultRequestHeaders.Accept.Add(
            new MediaTypeWithQualityHeaderValue("application/json"));
    }

    /// <summary>
    /// Makes the request to the SVC API. Ensures the autenthication
    /// </summary>
    /// <param name="apiParam">End point to be addressed. Generated by the controllers</param>
    /// <returns>Returns the HttpRequestMessage</returns>
    public static async Task<HttpResponseMessage> SvcGetAsync(string apiParam)
    {
        await SvcLoginAsync();
        
        DotNetEnv.Env.Load();
        var uri = Environment.GetEnvironmentVariable("SVC_API_URL") + apiParam;
        var response = await Client.GetAsync(uri);
        

        return response;
    }
    
    /// <summary>
    /// 
    /// </summary>
    /// <param name="apiParam">End point to be addressed. Generated by the controllers</param>
    /// <param name="content">The HTTP request content sent to the server.</param>
    public static async void SvcPostAsync(string apiParam, string content)
    {
        await SvcLoginAsync();
        
        DotNetEnv.Env.Load();
        var uri = Environment.GetEnvironmentVariable("SVC_API_URL") + apiParam;
        var requestContent = new StringContent(content, Encoding.UTF8, "application/json");
        await Client.PostAsync(uri, requestContent);
        
    }
        
    //Ist für den Login zuständig
    private static async Task SvcLoginAsync()
    {
        DotNetEnv.Env.Load();
        
        var body = new Dictionary<string, string?>
        {
           { "Login", Environment.GetEnvironmentVariable("SVC_USERNAME")},
           { "Password", Environment.GetEnvironmentVariable("SVC_PASSWORD") }
        };

        var content = new FormUrlEncodedContent(body);
        await Client.PostAsync(Environment.GetEnvironmentVariable("SVC_API_URL")+"Login", content);
    }
}